if(BUILD_TESTS STREQUAL "ON")
    add_compile_options(-fdump-rtl-expand)
    if (BSS_TEST_COVERAGE)
        message(STATUS "BUILD_TESTS = ON, add compile gov")
        add_compile_options(-fprofile-arcs -ftest-coverage)
        add_link_options(-lgcov --coverage)
    else()
        message(STATUS "BUILD_TESTS = ON, coverage disabled for perf build")
    endif()
    add_subdirectory(llt)
endif()